name: Kspider Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew :bootJar

  push:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - run: pwd
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        push: true
        tags: |
          kkangert/test:latest
          kkangert/test:${{ github.event.release.tag_name }}